version: '3.8'

services:
  app:
    image: nur-hidayati:latest
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "7860:7860"
    volumes:
      - ./finetune-indosum:/app/finetune-indosum
    environment:
      GRADIO_SERVER_NAME: "0.0.0.0"
    networks:
      net:
        ipv4_address: 10.0.0.20

  nginx:
    image: nginx:stable-alpine-slim
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./nginx_logs:/var/log/nginx
    depends_on:
      - app
    networks:
      net:
        ipv4_address: 10.0.0.10

networks:
  net:
    driver: bridge
    ipam:
      config:
        - subnet: 10.0.0.0/24